In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

data = [[1,1],[2,1],[5,2],[4,3]]

X : np.array = np.array(data)[:, 1:]

Y : np.array = np.array(data)[:,0].reshape(-1,1)




In [2]:
pd.DataFrame(np.array(data))

0  1
0  1  1
1  2  1
2  5  2
3  4  3

In [3]:
Y

array([[1],
       [2],
       [5],
       [4]])

In [4]:
X

array([[1],
       [1],
       [2],
       [3]])

In [5]:
linear_model = LinearRegression().fit(X=X, y=Y)

linear_model

LinearRegression()

In [6]:
linear_model.coef_.round(1).tolist()

[[1.5]]

In [7]:
linear_model.intercept_

array([0.45454545])

In [8]:

linear_model.predict(X)

array([[1.90909091],
       [1.90909091],
       [3.36363636],
       [4.81818182]])

In [9]:
from datetime import datetime, date
import numpy as np
# Example dates (replace with your actual dates)
dates = [date(2025, 2, 21), date(2025, 2, 22), date(2025, 2, 23)]
values = [10, 20, 30]

# Convert dates to timestamps
timestamps = [datetime.strptime(str(date), '%Y-%m-%d').timestamp() for date in dates]

In [10]:
(np.array(timestamps) - timestamps[0]) / (timestamps[1] - timestamps[0])

array([0., 1., 2.])

In [11]:
timestamps[1] - timestamps[0]

86400.0

In [31]:
import pandas as pd
data = np.array([[1,1,0],[2,1,1],[3,1,2],[4,1,3]])
X = data[:, 1:]
X

array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 3]])

In [32]:
y = data[:, 0]
y

array([1, 2, 3, 4])

In [40]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression().fit(X=X, y=y.reshape(-1,1))

lr.coef_.tolist()

[[0.0, 1.0000000000000002]]

In [30]:
lr.intercept_.tolist()

[0.9999999999999993]

In [41]:
lr.predict(X).round(1)

array([[1.],
       [2.],
       [3.],
       [4.]])

In [44]:

prediction = lr.predict(X).round(1)
prediction

array([[1.],
       [2.],
       [3.],
       [4.]])

In [35]:
[p[0] for p in prediction.tolist()]

[1.0, 2.0, 3.0, 4.0]